
services:
  mongo:
    image: mongo:latest
    container_name: mongo-sistemafinanciero
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: sistemafinanciero
    ports:
      - "27017:27017"
    networks:
      - sistema-financiero-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - sistema-financiero-net

networks:
  sistema-financiero-net:
    driver: bridge