#!/bin/bash

# Script para probar la funcionalidad de notificaciones
# Este script ayuda a entender el flujo de notificaciones

echo "================================================"
echo "🧪 PRUEBA DE NOTIFICACIONES - INSTRUCCIONES"
echo "================================================"
echo ""
echo "Para verificar que todo funciona correctamente:"
echo ""
echo "1️⃣  Asegúrate que el backend está corriendo:"
echo "   cd backend && npm start"
echo ""
echo "2️⃣  Asegúrate que el frontend está compilado:"
echo "   cd frontend && npm run build"
echo ""
echo "3️⃣  Abre el navegador y accede a:"
echo "   http://localhost:5173 (desarrollo) o donde esté el frontend"
echo ""
echo "4️⃣  Inicia sesión con dos usuarios diferentes:"
echo "   - Usuario 1: Juan Alvarez (juancarlos.alvarez2106@gmail.com)"
echo "   - Usuario 2: Juano Nano (juanalvarezjaja5@gmail.com)"
echo ""
echo "5️⃣  Desde Usuario 1, crea un gasto compartido:"
echo "   - Ve a la sección de Gastos/Ingresos"
echo "   - Clic en 'Nuevo Gasto Compartido'"
echo "   - Rellena los datos y selecciona a Usuario 2 como participante"
echo "   - Haz clic en 'Crear'"
echo ""
echo "6️⃣  En la pestaña de Usuario 2, deberías ver:"
echo "   ✅ Badge actualizado en el header (número de notificaciones)"
echo "   ✅ Sonido de alerta"
echo "   ✅ Nueva notificación en la sección de notificaciones"
echo ""
echo "7️⃣  Abre la consola del navegador (F12) y busca los logs:"
echo "   - 📡 [SeccionNotificaciones] Pidiendo notificaciones..."
echo "   - 📨 [SeccionNotificaciones] Respuesta recibida..."
echo "   - ✅ [SeccionNotificaciones] X notificaciones cargadas"
echo ""
echo "================================================"
echo ""
echo "📝 VERIFICACIÓN EN BASE DE DATOS:"
echo "Para verificar que las notificaciones se guardaron:"
echo "   node verificar-notificaciones.js"
echo ""
echo "Este script mostrará todas las notificaciones en MongoDB"
echo "y el conteo por usuario"
echo ""
echo "================================================"
